### PR TITLE
feat: add jetbrains-gateway

### LINKED ISSUE #2: JetBrains Gateway
## Must have

- [x] coder_app to open workspace in Gateway (https://github.com/coder/jetbrains-coder/pull/289)

## Should have 

- [x] Variables/icons for various IDEs 

@matifali feel free to expand

### PR DESCRIPTION
**Pull request by matifali**
Closes #2

- [x] Test
image

### CODE REVIEW

**Comment by bpmct** [comment]
What is the UX like? Does it open in a new tab and get stuck?

**Review by bpmct — APPROVED** [review]

**Comment by matifali** [comment]
@bpmct yeah it does open in a new tab that stays :/

**Comment by bpmct** [comment]
I see. You created https://github.com/coder/coder/issues/9752

**Comment by bpmct** [comment]
I noticed in the screenshot two of the images did not resolve. I'm not sure if that was fixed, but if so, this is good to merge!

**Comment by matifali** [comment]
@bpmct this was tested on an old deployment where those icons are not available on dev.coder.com all icons show up.

**Comment by kylecarbs** [comment]
@matifali you'll have to re-open on `main`, I didn't realize my force-push would close this :( won't do again

**Pull request closed without merging**
